import re
import unicodedata
from rapidfuzz import fuzz
from playwright.sync_api import sync_playwright


def normalize_key(s: str) -> str:
    s = "" if s is None else str(s)
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode("ascii")
    s = s.upper()
    s = re.sub(r"[^A-Z0-9 ]+", " ", s)
    return re.sub(r"\s+", " ", s).strip()


def clean_list(items):
    out = []
    for x in items:
        x = re.sub(r"\s+", " ", str(x)).strip()
        if not x:
            continue
        if "INCONNU" in x.upper():
            continue
        if x not in out:
            out.append(x)
    return out


def parse_sacem_detail(text: str) -> dict:
    lines = [l.strip() for l in text.splitlines() if l.strip()]

    title = ""
    authors = []
    composers = []
    publishers = []
    sub_publishers = []
    performers = []
    iswc = ""

    if "Retour aux résultats" in lines:
        idx = lines.index("Retour aux résultats")
        if idx + 1 < len(lines):
            title = lines[idx + 1]

    for line in lines:
        if "Code ISWC" in line:
            iswc = line.replace("Code ISWC :", "").replace("Code ISWC:", "").strip()

        if ", Compositeur-Auteur" in line:
            name = line.replace(", Compositeur-Auteur", "").strip()
            authors.append(name)
            composers.append(name)

        elif ", Compositeur" in line:
            composers.append(line.replace(", Compositeur", "").strip())

        elif ", Auteur" in line:
            authors.append(line.replace(", Auteur", "").strip())

        elif ", Editeur" in line:
            publishers.append(line.replace(", Editeur", "").strip())

        elif ", Sous Editeur" in line:
            sub_publishers.append(line.replace(", Sous Editeur", "").strip())

    if "INTERPRÈTE" in lines:
        idx = lines.index("INTERPRÈTE")
        if idx + 1 < len(lines):
            performers.append(lines[idx + 1])

    return {
        "status": "found",
        "title": title,
        "iswc": iswc,
        "authors": clean_list(authors),
        "composers": clean_list(composers),
        "publishers": clean_list(publishers),
        "sub_publishers": clean_list(sub_publishers),
        "performers": clean_list(performers),
    }


class SacemAgent:
    def __init__(self, headless=True):
        self.headless = headless

    def _is_blocked(self, body_text: str) -> bool:
        text = str(body_text or "").lower()

        return (
            "403 error" in text
            or "request blocked" in text
            or "generated by cloudfront" in text
            or "the request could not be satisfied" in text
        )

    def _open_home_and_accept_cookies(self, page) -> str:
        page.goto(
            "https://repertoire.sacem.fr/",
            wait_until="domcontentloaded",
            timeout=60000,
        )

        page.wait_for_timeout(2000)

        body_text = page.locator("body").inner_text()

        if self._is_blocked(body_text):
            return body_text

        try:
            page.get_by_text(
                "Accepter les cookies",
                exact=False,
            ).click(timeout=2500)
        except Exception:
            pass

        return page.locator("body").inner_text()

    def _run_search(
        self,
        page,
        title: str,
        artist: str = "",
    ) -> str:
        body_text = self._open_home_and_accept_cookies(page)

        print("SACEM URL:", page.url)
        print("SACEM BODY:", body_text[:1000])

        if self._is_blocked(body_text):
            return body_text

        inputs = page.locator("input:visible")

        if inputs.count() < 2:
            return body_text

        print("TITLE =", title)
        print("ARTIST =", artist)

        inputs.nth(0).fill(title)
        inputs.nth(1).fill(artist or "")

        search_button = page.locator("#searchBtn")

        if search_button.count() == 0:
            return page.locator("body").inner_text()

        search_button.click()

        try:
            page.wait_for_url(
                "**/resultats**",
                timeout=15000,
            )
        except Exception:
            pass

        page.wait_for_timeout(2500)

        return page.locator("body").inner_text()

    def _has_results(self, body_text: str) -> bool:
        text = str(body_text or "").lower()

        return (
            "œuvre correspondante" in text
            or "oeuvre correspondante" in text
            or "voir le détail" in text
        )

    def _extract_candidate_title(self, block_text: str) -> str:
        lines = [
            line.strip()
            for line in str(block_text or "").splitlines()
            if line.strip()
        ]

        ignored = {
            "VOIR LE DÉTAIL",
            "VOIR LE DETAIL",
            "ŒUVRE",
            "OEUVRE",
        }

        for line in lines:
            if normalize_key(line) not in ignored:
                return line

        return lines[0] if lines else ""

    def _choose_result_index_from_page(
        self,
        page,
        title: str,
        artist: str = "",
    ) -> int:
        wanted_title = normalize_key(title)
        wanted_artist = normalize_key(artist)

        detail_links = self._get_detail_links(page)

        count = detail_links.count()
        print("SACEM RESULT COUNT:", count)

        best_index = 0
        best_score = -1

        for index in range(count):
            link = detail_links.nth(index)

            block = link.locator(
                "xpath=ancestor::*"
                "[self::div or self::article or self::li]"
                "[.//*[contains("
                "normalize-space(.), "
                "'VOIR LE DÉTAIL'"
                ")]][1]"
            )

            try:
                block_text = block.inner_text(timeout=3000)
            except Exception:
                block_text = ""

            result_title_raw = self._extract_candidate_title(
                block_text
            )

            result_title = normalize_key(result_title_raw)
            block_key = normalize_key(block_text)

            if not result_title:
                continue

            title_score = fuzz.ratio(
                wanted_title,
                result_title,
            )

            artist_score = 0

            if wanted_artist:
                artist_score = fuzz.partial_ratio(
                    wanted_artist,
                    block_key,
                )

            if result_title == wanted_title:
                score = 100000 + artist_score
            else:
                score = title_score * 100 + artist_score

            print(
                "SACEM CANDIDATE:",
                index,
                "TITLE:",
                result_title_raw,
                "TITLE SCORE:",
                title_score,
                "ARTIST SCORE:",
                artist_score,
                "TOTAL:",
                score,
            )

            if score > best_score:
                best_score = score
                best_index = index

        # Important : en dehors de la boucle.
        return best_index
    def _get_detail_links(self, page):
        links = page.locator(
        "a:has-text('VOIR LE DÉTAIL'), "
        "button:has-text('VOIR LE DÉTAIL'), "
        "[role='button']:has-text('VOIR LE DÉTAIL')"
    )

        if links.count() == 0:
            links = page.get_by_text(
                "VOIR LE DÉTAIL",
                exact=False,
            )

        return links
    def search(
        self,
        title: str,
        artist: str = "",
    ) -> dict:
        title = str(title or "").strip()
        artist = str(artist or "").strip()

        with sync_playwright() as playwright:
            browser = playwright.chromium.launch(
             headless=False,
            )

            page = browser.new_page(
                viewport={
                    "width": 1450,
                    "height": 900,
                },
                locale="fr-FR",
            )

            try:
                body_text = self._run_search(
                    page,
                    title,
                    artist,
                )

                if self._is_blocked(body_text):
                    return {
                        "status": "blocked",
                        "title": "",
                        "iswc": "",
                        "authors": [],
                        "composers": [],
                        "publishers": [],
                        "sub_publishers": [],
                        "performers": [],
                        "title_input": title,
                        "artist_input": artist,
                        "search_mode": "title_artist",
                        "url": page.url,
                        "raw_text": body_text[:2000],
                    }

                search_mode = "title_artist"
                search_url = page.url

                if not self._has_results(body_text):
                    body_text = self._run_search(
                        page,
                        title,
                        "",
                    )

                    search_mode = "title_only_fallback"
                    search_url = page.url

                    if self._is_blocked(body_text):
                        return {
                            "status": "blocked",
                            "title": "",
                            "iswc": "",
                            "authors": [],
                            "composers": [],
                            "publishers": [],
                            "sub_publishers": [],
                            "performers": [],
                            "title_input": title,
                            "artist_input": artist,
                            "search_mode": search_mode,
                            "url": page.url,
                            "raw_text": body_text[:2000],
                        }

                detail_links = self._get_detail_links(page)

                count = detail_links.count()

                if count == 0:
                    return {
                        "status": "not_found",
                        "title": "",
                        "iswc": "",
                        "authors": [],
                        "composers": [],
                        "publishers": [],
                        "sub_publishers": [],
                        "performers": [],
                        "title_input": title,
                        "artist_input": artist,
                        "search_mode": search_mode,
                        "url": "",
                        "search_url": search_url,
                        "raw_text": body_text[:2000],
                    }

                selected_index = (
                    self._choose_result_index_from_page(
                        page,
                        title,
                        artist
                        if search_mode == "title_artist"
                        else "",
                    )
                )

                if selected_index >= count:
                    selected_index = 0

                detail_links.nth(
                    selected_index
                ).click()

                try:
                    page.wait_for_url(
                        "**/detail-oeuvre/**",
                        timeout=10000,
                    )
                except Exception:
                    pass

                page.wait_for_timeout(2000)

                current_url = page.url

                if "/detail-oeuvre/" not in current_url:
                    return {
                        "status": "not_found",
                        "title": "",
                        "iswc": "",
                        "authors": [],
                        "composers": [],
                        "publishers": [],
                        "sub_publishers": [],
                        "performers": [],
                        "title_input": title,
                        "artist_input": artist,
                        "search_mode": search_mode,
                        "url": "",
                        "result_count": count,
                        "selected_result_index": (
                            selected_index
                        ),
                        "search_url": search_url,
                    }

                current_title = page.title()

                detail_text = page.locator(
                    "body"
                ).inner_text()

                parsed = parse_sacem_detail(
                    detail_text
                )

                returned_title = parsed.get(
                    "title",
                    "",
                )

                title_score = fuzz.ratio(
                    normalize_key(title),
                    normalize_key(returned_title),
                )

                parsed["title_match_score"] = (
                    title_score
                )

                if title_score < 85:
                    parsed["status"] = "not_found"
                    parsed["url"] = ""
                else:
                    parsed["status"] = "found"
                    parsed["url"] = current_url

                parsed["artist_input"] = artist
                parsed["title_input"] = title
                parsed["search_mode"] = search_mode
                parsed["page_title"] = current_title
                parsed["result_count"] = count
                parsed["selected_result_index"] = (
                    selected_index
                )
                parsed["search_url"] = search_url

                return parsed

            finally:
                browser.close()


if __name__ == "__main__":
    agent = SacemAgent(headless=True)

    result = agent.search(
        "BOOK CLUB REUNION",
        "Tom Howe",
    )

    print(result)